##########
# Reverse proxy for facilitating serving the static UI files and the flask API
###########

FROM nginx:1.17-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx-prod.conf /etc/nginx/conf.d

# Copy Certs
COPY certs/fullchain.pem /etc/nginx/certs/fullchain.pem
COPY certs/privkey.pem /etc/nginx/certs/privkey.pem
